# Generated by Django 5.2.9 on 2025-12-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('current_message', models.CharField(blank=True, max_length=200, null=True)),
                ('message_type', models.CharField(default='info', max_length=50)),
            ],
        ),
    ]
